import test from 'node:test';import assert from 'node:assert/strict';
import {assistWithJev,reorderWithAssist,resetJevState,JEV_MODEL} from '../lib/jev.ts';
const cs=[{hts:'1',description:'glass cups',hierarchyParts:'glass'},{hts:'2',description:'ceramic mugs',hierarchyParts:'ceramic tableware'}];
function reply(status=200,body:any={model:JEV_MODEL,answers:{best_candidate:{choice:'candidate_1',confidence:.9},facts_sufficient:{noul:.8},fit_0:{noul:.2},fit_1:{noul:.91}},usage:{input_tokens:1000}}){return async()=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}})}
test('off by default',async()=>{delete process.env.JEV_AI_ENABLED;assert.equal((await assistWithJev('ceramic mug',cs,reply() as any)).status,'off')});
test('reranks only a validated candidate',async()=>{process.env.JEV_AI_ENABLED='true';process.env.JEV_API_KEY='test';resetJevState();const a=await assistWithJev('ceramic mug',cs,reply() as any);assert.equal(a.status,'ok');assert.equal(reorderWithAssist(cs,a)[0].hts,'2');assert.equal(a.estimatedCostUsd,.000042)});
test('low sufficiency abstains',async()=>{process.env.JEV_AI_ENABLED='true';process.env.JEV_API_KEY='test';resetJevState();const b:any={model:JEV_MODEL,answers:{best_candidate:{choice:'candidate_1',confidence:.9},facts_sufficient:{noul:.2},fit_0:{noul:.1},fit_1:{noul:.9}},usage:{input_tokens:500}};assert.equal((await assistWithJev('mug',cs,reply(200,b) as any)).status,'inconclusive')});
test('API failure preserves fallback status',async()=>{process.env.JEV_AI_ENABLED='true';process.env.JEV_API_KEY='test';resetJevState();assert.equal((await assistWithJev('mug',cs,reply(401,{}) as any)).status,'temporarily_unavailable')});
test('identical request is cached',async()=>{process.env.JEV_AI_ENABLED='true';process.env.JEV_API_KEY='test';resetJevState();let n=0;const f=async()=>{n++;return (reply() as any)()};await assistWithJev('ceramic mug',cs,f as any);const a=await assistWithJev('ceramic mug',cs,f as any);assert.equal(a.status,'cached');assert.equal(n,1)});
